### ISSUE TITLE
Unable to assign AXIS_HAT_X AXIS_HAT_Y

### ISSUE THREAD

**Issue by neoteknic** [mupen64plus-ae/mupen64plus-ae#339]
Hello with my ipega 9025 controler I'm nable to assign the  AXIS_HAT_X, AXIS_HAT_Y to the digital cross on the N64, (it is the digital cross on the ipega controler, and you can navigate with this cross on android menus).
The key assign menu don't react on keypress only with the digital cross on the ipega.
On the controler diagnostic, the cross work fine, it's named AXIS_HAT_X, AXIS_HAT_Y (joystick), and can take values of 0 , +1.00 or -1.00.

**Comment by serrast** [comment]
Hey, Littleguy77- 

I'm having the same issue described by OP - left thumbstick axis_hat ignored. Idemtical to OPs second screenshot. But I just installed MegaN64 from the play store today (3 years later).

Am I missing some other way to map the left thumbstick to movement, or do I need to uninstall and grab your APK from this thread?

Thanks

BTW, using NES30 Pro controller on Galaxy S7 nougat.

**Comment by fzurita** [comment]
Please download this version: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita&hl=en

That's the latest version of the app. I have fixed several controller issues.

**Comment by theShrike760** [comment]
This issue still exists. I am running the latest 131 build on an amazon fire box with a PS4 controller. The analog sticks won't map but are shown on diagnostics screen and work when navigating the app menus.

**Comment by fzurita** [comment]
Very strange issue. I have a PS4 controller and all axis map correctly in a NVidia Shield TV. This will be hard to debug, can you send me a screenshot of your controller diagnostic after using the analog sticks?

**Comment by Ezalech** [comment]
I'm had te same issue on Mega64, and the only way to fix it was downloading the Mupen64Plus FZ.  BUT it is much laggier than Mega64. Its getting some FPS drops (18 fps sometimes) while on Mega64 I didnt have this problem.

**Comment by fzurita** [comment]
What game is giving you performance issues with Mupen64plus FZ? What device do you have?

**Comment by Ezalech** [comment]
With both Mario Kart and Super Smash ( the only ones I tested). Its a Moto G5 plus.

**Comment by fzurita** [comment]
Interesting. That device should play those games full speed. Did you try switching to another emulation profile like GLideN64-Medium?

**Comment by Ezalech** [comment]
Yea it played at full speed as Mega64. Nope I did not try that. Is it an in-app setting? Or another app?

**Comment by fzurita** [comment]
While looking at the gallery, open up the sidebar by selecting the top left menu. Go to profiles, then select emulation profiles. In there, ty switching the default to "GLideN64-Medium".

**Comment by fzurita** [comment]
Other things you can try:
* Go to settings then input, choose "high priority" mode.
* Go to settings then audio, disable "synchronize audio and video".
* In that same screen, try setting sampling rate to "best for hardware"

**Comment by Ezalech** [comment]
It probably fixed the FPS drop, but Im still getting 26 fps max... Is that the best it can get?

**Comment by Ezalech** [comment]
I say probably cause it happened occasionally.

**Comment by fzurita** [comment]
Which game is giving you 26fps Max?

**Comment by Ezalech** [comment]
Mario Kart... ill test Smash

**Comment by Ezalech** [comment]
Smash is pretty slow... Its acting like its game speed is set to 75%... But FPS surpass 30 at least.

**Comment by fzurita** [comment]
It does seem odd. The games are not reaching full speed in your device. Your device should be capable. Mario kart should be running at 30fps. Can you try the Glide64-Fast emulation profile? I believe MegaN64 defaults to that one.

**Comment by fzurita** [comment]
Also, smash brothers is a 60fps game.

**Comment by Ezalech** [comment]
It's still getting 30 FPS on Smash, and some times 46, or 14 (lagging)...

**Comment by Ezalech** [comment]
Tested MEGA to be sure and it almost get 70fps.

**Comment by fzurita** [comment]
Ok, I think I found a problem. Can you download the latest app version and see if it improves your fps with Glide64?

**Comment by Ezalech** [comment]
Wow just updated... Are you the dev?

**Comment by fzurita** [comment]
I'm one of many developers. I'm the publisher in the play store of Mupen64plus FZ

**Comment by Ezalech** [comment]
So you did that for me :D ?
Jk hahaha thx man, Ill test it out later and tell you later.

**Comment by fzurita** [comment]
Well, if it affects you, it could affect many people. No problem!

**Comment by Ezalech** [comment]
Ok, Using Glide64-Fast is getting 60fps on menus but on match (smash) it is 46 fps and running like its game speed is set to slow...

**Comment by fzurita** [comment]
Hmm... ok, I'll try to see what's up with that game.

**Comment by Ezalech** [comment]
Mario Kart is getting 26 (that is not a problem for me actually) but it runs ok, At least no problem for now...

**Comment by fzurita** [comment]
Ok, another update had been made. I don't expect any improvements to your highest FPS for Glide64. There game shouldn't feel like slow motion though.

**Comment by Ezalech** [comment]
It's still in slow motion :(

**Comment by fzurita** [comment]
With Glide64-Fast?

**Comment by Ezalech** [comment]
Yea

**Comment by fzurita** [comment]
Hmm, interesting. I tested several devices and it seemed to work ok... I guess there are always some devices that behave differently.

Could you try making a custom Glide64 emulation profile and setting the max frame skip to 5?

**Comment by fzurita** [comment]
I don't think installing the app again would help.

**Comment by Ezalech** [comment]
Made the custom profile, but didn't do anything..

**Comment by fzurita** [comment]
Ok, thanks. I guess there is not much I can do to help with your device without actually owning it.

**Comment by Ezalech** [comment]
:( Ok thx anyway.

**Comment by Narolex** [comment]
Hello! I have MegaN64 in Samsung Galaxy Note 2 but I can not assign D-pad buttons in my gamepad D-pad. Do you know how to fix the problema? Thank you so much. I can assig the D-pad buttons in other emulators with no problem.

**Comment by fzurita** [comment]
Hello, we don't support MegaN64. It's also using an outdated version of our source.

Please try the more official listing right here: https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by Narolex** [comment]
I do not have this problem with SuperN64

**Comment by fzurita** [comment]
Ok, SuperN64 is also a clone of our app. We can't do anything to fix MegaN64, you will have to contact them. The best I can tell you to do is use this version of the app which won't have that problem:
https://play.google.com/store/apps/details?id=org.mupen64plusae.v3.fzurita

**Comment by Narolex** [comment]
Okey! Thank you so much! ^_^
