### ISSUE TITLE
Marshmallow Permissions

### ISSUE THREAD

**Issue by xperia64** [mupen64plus-ae/mupen64plus-ae#533]
Seeing as we are now targeting Marshmallow, we need to dynamically request external storage permissions. Users can manually grant these, but most users do not actually know how to use the permissions menu in Settings. I personally would recommend explicitly declaring READ_EXTERNAL_STORAGE as well.

**Comment by fzurita** [comment]
I committed the change, but I have no way to try it since I don't have a 6.0 device. It sounds like you do, can you try it out?

**Comment by xperia64** [comment]
That is only part of the solution. The app still fails unless I manually grant the storage permission in settings. On Marshmallow, we must explicitly ask users to grant permissions and verify that the permission is still held every run.
For an example, see my own implementation:
https://github.com/xperia64/timidity-ae/blob/3.0/src/com/xperia64/timidityae/TimidityActivity.java#L243
https://github.com/xperia64/timidity-ae/blob/3.0/src/com/xperia64/timidityae/TimidityActivity.java#L303

**Comment by fzurita** [comment]
Ok, done. See e86f3f56820cac06bab20e52823f98d8b10d4fb6.
